
# Ne pas modifier ce fichier

# Composant: Plugin
package Ident;
use strict;
use warnings;

  sub Alias_NewArray { return 'Id_584'; }
  sub Alias_BadIncludeNames { return 'Id_509'; }
  sub Alias_NotExists { return 'Id_453'; }
  sub Alias_Pipes { return 'Id_006'; }
  sub Alias_ExceptionWhen { return 'Id_005'; }
  sub Alias_DiffUpdate { return 'Id_007'; }
  sub Alias_ParamTags { return 'Id_008'; }
  sub Alias_SQL { return 'Id_454'; }
  sub Alias_IEConditionalComments { return 'Id_642'; }
  sub Alias_CaseWhen { return 'Id_012'; }
  sub Alias_BadIncDecUse { return 'Id_553'; }
  sub Alias_IllegalStatements { return 'Id_013'; }
  sub Alias_BadSpacingInFuncDecl { return 'Id_646'; }
  sub Alias_ShellLauncherFunctionCalls { return 'Id_014'; }
  sub Alias_StandardTableModifications { return 'Id_510'; }
  sub Alias_PragmaMark { return 'Id_621'; }
  sub Alias_JSPComment { return 'Id_700'; }
  sub Alias_CodeCheckDisabling { return 'Id_511'; }
  sub Alias_Base_Goto { return 'Id_016'; }
  sub Alias_WithReturnOutsideExceptionHandler_Function { return 'Id_017'; }
  sub Alias_SQLDeclareView { return 'Id_484'; }
  sub Alias_Base_Others { return 'Id_019'; }
  sub Alias_ForwardClass { return 'Id_635'; }
  sub Alias_UnrefInternalProc { return 'Id_455'; }
  sub Alias_ParaNameWithoutDot { return 'Id_382'; }
  sub Alias_Getpass { return 'Id_585'; }
  sub Alias_VariableArgumentMethods { return 'Id_022'; }
  sub Alias_Type_Positiven { return 'Id_021'; }
  sub Alias_WithoutVirtualDestructorAbstractClass { return 'Id_586'; }
  sub Alias_FunctionCallInForLoopTest { return 'Id_554'; }
  sub Alias_ProcedureImplementations { return 'Id_023'; }
  sub Alias_Conditions { return 'Id_669'; }
  sub Alias_PD_ProhibitedKeyword { return 'Id_385'; }
  sub Alias_WhileLoop { return 'Id_456'; }
  sub Alias_UnCommentedViews { return 'Id_487'; }
  sub Alias_ArgumentCallee { return 'Id_663'; }
  sub Alias_LinesOfText { return 'Id_704'; }
  sub Alias_BadSelectorCaching { return 'Id_655'; }
  sub Alias_Base_Elsif { return 'Id_039'; }
  sub Alias_NSLog { return 'Id_637'; }
  sub Alias_UntilLoop { return 'Id_457'; }
  sub Alias_StdScriptlet { return 'Id_672'; }
  sub Alias_RefToMe { return 'Id_512'; }
  sub Alias_Sql_Declare { return 'Id_043'; }
  sub Alias_MissingSemicolon { return 'Id_661'; }
  sub Alias_UnassignedObjectInstanciation { return 'Id_555'; }
  sub Alias_SeriousFilePb { return 'Id_387'; }
  sub Alias_Basex_Function { return 'Id_045'; }
  sub Alias_OpenDataset { return 'Id_513'; }
  sub Alias_IsNullInWhereClause { return 'Id_514'; }
  sub Alias_EmptyRenames { return 'Id_389'; }
  sub Alias_Free { return 'Id_046'; }
  sub Alias_PointerObjectParameters { return 'Id_053'; }
  sub Alias_DBUsedObjects { return 'Id_488'; }
  sub Alias_BadArrayDeclaration { return 'Id_648'; }
  sub Alias_AssignmentToThis { return 'Id_556'; }
  sub Alias_Type_Lob { return 'Id_055'; }
  sub Alias_UnparenthesedParamMacros { return 'Id_057'; }
  sub Alias_TopLevelAnonymousBlocs { return 'Id_058'; }
  sub Alias_MissingFinalElses { return 'Id_061'; }
  sub Alias_MultilineReturn { return 'Id_656'; }
  sub Alias_OnChangeOf { return 'Id_515'; }
  sub Alias_MultInstOnLine { return 'Id_391'; }
  sub Alias_Try { return 'Id_480'; }
  sub Alias_Segments { return 'Id_062'; }
  sub Alias_SQLSelectStar { return 'Id_392'; }
  sub Alias_WeakStringFunctionCalls { return 'Id_064'; }
  sub Alias_MissingSetter { return 'Id_557'; }
  sub Alias_Pd_CptComment { return 'Id_393'; }
  sub Alias_RuleOf3_WithDestructor { return 'Id_587'; }
  sub Alias_Type_Natural { return 'Id_067'; }
  sub Alias_MissingJSPComment { return 'Id_691'; }
  sub Alias_Open { return 'Id_069'; }
  sub Alias_UnecessaryNestedObjectResolution { return 'Id_650'; }
  sub Alias_BadProgramNames { return 'Id_516'; }
  sub Alias_MissingScalarType { return 'Id_657'; }
  sub Alias_BadZoneDecl { return 'Id_394'; }
  sub Alias_WithNotConstRefParametersOperators { return 'Id_074'; }
  sub Alias_Foreach { return 'Id_075'; }
  sub Alias_MixedTagFormat { return 'Id_688'; }
  sub Alias_TotalColumns { return 'Id_494'; }
  sub Alias_Union { return 'Id_077'; }
  sub Alias_Type_Boolean { return 'Id_076'; }
  sub Alias_UsingByValuePassing_Forms { return 'Id_517'; }
  sub Alias_SQLMissingTest { return 'Id_395'; }
  sub Alias_MissingEndPERFORM { return 'Id_396'; }
  sub Alias_BadCaseKeyword { return 'Id_079'; }
  sub Alias_MissingBreakInCasePath { return 'Id_082'; }
  sub Alias_Continue { return 'Id_083'; }
  sub Alias_Case { return 'Id_084'; }
  sub Alias_TagLib { return 'Id_674'; }
  sub Alias_DBObjectUsingRef { return 'Id_495'; }
  sub Alias_ExportedVariables { return 'Id_087'; }
  sub Alias_AnonymousNamespaces { return 'Id_088'; }
  sub Alias_Base_Exit { return 'Id_089'; }
  sub Alias_IF { return 'Id_397'; }
  sub Alias_Fc_NbFile { return 'Id_398'; }
  sub Alias_Type_Integer { return 'Id_090'; }
  sub Alias_Repeat { return 'Id_094'; }
  sub Alias_ZeroParameterProcedures { return 'Id_369'; }
  sub Alias_Type_Varchar2 { return 'Id_097'; }
  sub Alias_Friends { return 'Id_100'; }
  sub Alias_PrivateProtectedAttributes { return 'Id_102'; }
  sub Alias_UselessOverridingMethod { return 'Id_558'; }
  sub Alias_MissingIdenticalOperator { return 'Id_559'; }
  sub Alias_FunctionDeclarations { return 'Id_103'; }
  sub Alias_HeterogeneousEncoding { return 'Id_105'; }
  sub Alias_EmptyStatementBloc { return 'Id_560'; }
  sub Alias_ClassDefinitions { return 'Id_108'; }
  sub Alias_Next { return 'Id_112'; }
  sub Alias_ShortConstNamesLT { return 'Id_113'; }
  sub Alias_MaxParameters { return 'Id_114'; }
  sub Alias_SeeTags { return 'Id_115'; }
  sub Alias_ShortAttributeNamesLT { return 'Id_116'; }
  sub Alias_BadSetInterval { return 'Id_666'; }
  sub Alias_Type_Varchar { return 'Id_117'; }
  sub Alias_ShortObjcClassName { return 'Id_617'; }
  sub Alias_PICNotAlign { return 'Id_400'; }
  sub Alias_WithoutPrimaryKeyTables { return 'Id_497'; }
  sub Alias_Evaluate { return 'Id_402'; }
  sub Alias_ShortFunctionNamesLT { return 'Id_121'; }
  sub Alias_CheckedArgs { return 'Id_123'; }
  sub Alias_UntrustedInputData { return 'Id_707'; }
  sub Alias_IfPrepro { return 'Id_124'; }
  sub Alias_Gosub { return 'Id_129'; }
  sub Alias_Sql_Close { return 'Id_130'; }
  sub Alias_DeclWithoutIdent { return 'Id_403'; }
  sub Alias_RepeatInVarInit { return 'Id_461'; }
  sub Alias_Type_Float { return 'Id_134'; }
  sub Alias_MultipleAssignments { return 'Id_135'; }
  sub Alias_BadFileExtension { return 'Id_675'; }
  sub Alias_LongLines100 { return 'Id_137'; }
  sub Alias_Sql_Open { return 'Id_140'; }
  sub Alias_FunctionMethodImplementations { return 'Id_142'; }
  sub Alias_MissingEndIf { return 'Id_405'; }
  sub Alias_Calloc { return 'Id_145'; }
  sub Alias_NotNullVariables { return 'Id_149'; }
  sub Alias_Pd_NbPerform { return 'Id_406'; }
  sub Alias_HtmlLOC { return 'Id_681'; }
  sub Alias_RuleOf3_WithCopyConstructor { return 'Id_588'; }
  sub Alias_ShortGlobalNamesLT { return 'Id_151'; }
  sub Alias_Sql_Modify { return 'Id_518'; }
  sub Alias_UnusedThrowsTags { return 'Id_561'; }
  sub Alias_UninitializedLocalVariables { return 'Id_152'; }
  sub Alias_StaticGlobalVariableInHeader { return 'Id_589'; }
  sub Alias_WithTooMuchParametersMethods_old { return 'Id_354'; }
  sub Alias_AsmLines { return 'Id_154'; }
  sub Alias_ShortObjcMethodName { return 'Id_618'; }
  sub Alias_ObsoleteKeywordED { return 'Id_407'; }
  sub Alias_Sql_Create { return 'Id_158'; }
  sub Alias_MultipleInstructions { return 'Id_157'; }
  sub Alias_BadBlockNames { return 'Id_639'; }
  sub Alias_Sql_Fetch { return 'Id_159'; }
  sub Alias_BadInitMove { return 'Id_410'; }
  sub Alias_CopyAssignableAbstractClass { return 'Id_590'; }
  sub Alias_Sql_Trigger { return 'Id_162'; }
  sub Alias_ProtectedAttributes { return 'Id_165'; }
  sub Alias_LongLines80 { return 'Id_164'; }
  sub Alias_MultipleBreakLoops { return 'Id_166'; }
  sub Alias_BlkSize { return 'Id_465'; }
  sub Alias_Sql_Insert { return 'Id_167'; }
  sub Alias_UnexpectedIvar { return 'Id_624'; }
  sub Alias_Elsif { return 'Id_169'; }
  sub Alias_BadTldLocation { return 'Id_677'; }
  sub Alias_ObsoleteKeywordWS { return 'Id_415'; }
  sub Alias_SignType { return 'Id_170'; }
  sub Alias_Type_Naturaln { return 'Id_171'; }
  sub Alias_Do { return 'Id_172'; }
  sub Alias_AuthorityCheck { return 'Id_519'; }
  sub Alias_Base_Raise { return 'Id_173'; }
  sub Alias_Nvarchar2Variable { return 'Id_175'; }
  sub Alias_UnnecessaryDeclarationTag { return 'Id_685'; }
  sub Alias_WellDeclaredVariables { return 'Id_176'; }
  sub Alias_UnusedParameters { return 'Id_562'; }
  sub Alias_SQLDeclareTable { return 'Id_417'; }
  sub Alias_WithoutFinalExit { return 'Id_177'; }
  sub Alias_ComplexMethodsLT { return 'Id_178'; }
  sub Alias_NewMethodImplementation { return 'Id_613'; }
  sub Alias_GlobalDefinitions { return 'Id_181'; }
  sub Alias_IndentedLines { return 'Id_183'; }
  sub Alias_WithoutSymbolNumerics { return 'Id_184'; }
  sub Alias_Sql_Cursor { return 'Id_185'; }
  sub Alias_Base_Exception { return 'Id_186'; }
  sub Alias_DeleteThis { return 'Id_591'; }
  sub Alias_MissingTableAlias { return 'Id_501'; }
  sub Alias_UnCommentedParameters { return 'Id_500'; }
  sub Alias_OutOfFinallyJumps { return 'Id_188'; }
  sub Alias_TriggerImplementations { return 'Id_189'; }
  sub Alias_MacroDefinitions { return 'Id_192'; }
  sub Alias_ShortFunctionNamesHT { return 'Id_193'; }
  sub Alias_Include { return 'Id_194'; }
  sub Alias_BadEffectiveFirstParameter { return 'Id_358'; }
  sub Alias_TooDepthArtifact { return 'Id_520'; }
  sub Alias_MultipleInheritances { return 'Id_197'; }
  sub Alias_ClassesComparisons { return 'Id_199'; }
  sub Alias_Alias { return 'Id_200'; }
  sub Alias_Then { return 'Id_202'; }
  sub Alias_ApplicationGlobalVariables { return 'Id_205'; }
  sub Alias_MissingClassDestructor { return 'Id_207'; }
  sub Alias_ObsoleteKeywordIOS { return 'Id_427'; }
  sub Alias_BadFileLocation { return 'Id_676'; }
  sub Alias_MagicString { return 'Id_210'; }
  sub Alias_Keywords { return 'Id_212'; }
  sub Alias_While { return 'Id_213'; }
  sub Alias_For { return 'Id_214'; }
  sub Alias_ShortMethodNamesLT { return 'Id_215'; }
  sub Alias_IllegalOperatorOverload { return 'Id_592'; }
  sub Alias_ModifiedIFS { return 'Id_217'; }
  sub Alias_IntoCorrespondingFieldsOf { return 'Id_521'; }
  sub Alias_BadClassNames { return 'Id_219'; }
  sub Alias_SQLGroupby { return 'Id_428'; }
  sub Alias_PublicAttributes { return 'Id_220'; }
  sub Alias_ImpliedGlobalVar { return 'Id_658'; }
  sub Alias_UnparametrizedNext { return 'Id_224'; }
  sub Alias_ExternalReferences { return 'Id_360'; }
  sub Alias_NcharVariable { return 'Id_226'; }
  sub Alias_MissingDefaults { return 'Id_364'; }
  sub Alias_RiskyFunctionCalls { return 'Id_228'; }
  sub Alias_Basex_Procedure { return 'Id_230'; }
  sub Alias_GroupBy { return 'Id_469'; }
  sub Alias_NoCopyClause { return 'Id_429'; }
  sub Alias_LinesOfScript { return 'Id_705'; }
  sub Alias_VariableDeclarations { return 'Id_231'; }
  sub Alias_ComplexConditions { return 'Id_232'; }
  sub Alias_Dbms_Sql_Parse { return 'Id_233'; }
  sub Alias_ShortIdentifiers { return 'Id_234'; }
  sub Alias_WithMissingParametersModes_Routines { return 'Id_235'; }
  sub Alias_MisplacedFunctionDecl { return 'Id_644'; }
  sub Alias_ValueNotAlign { return 'Id_430'; }
  sub Alias_ClassImplementations { return 'Id_236'; }
  sub Alias_XmlExpression { return 'Id_697'; }
  sub Alias_Strecpy { return 'Id_593'; }
  sub Alias_Background { return 'Id_237'; }
  sub Alias_SelectForUpdate { return 'Id_523'; }
  sub Alias_Basex_Package { return 'Id_239'; }
  sub Alias_With { return 'Id_664'; }
  sub Alias_LinesInSpec { return 'Id_352'; }
  sub Alias_WithinBlocksFunctionsDecl { return 'Id_643'; }
  sub Alias_MagicNumbers { return 'Id_244'; }
  sub Alias_SqlLines { return 'Id_245'; }
  sub Alias_MissingEndComment { return 'Id_563'; }
  sub Alias_NotIn { return 'Id_471'; }
  sub Alias_Strlen { return 'Id_594'; }
  sub Alias_ObsoleteKeywordFS { return 'Id_434'; }
  sub Alias_PackageAttributes { return 'Id_638'; }
  sub Alias_Sql_Select { return 'Id_247'; }
  sub Alias_Fill { return 'Id_248'; }
  sub Alias_XmlDeclaration { return 'Id_695'; }
  sub Alias_BadMainProcedureName { return 'Id_472'; }
  sub Alias_MissingCDATA { return 'Id_682'; }
  sub Alias_ForEach { return 'Id_252'; }
  sub Alias_WithoutValueExit { return 'Id_253'; }
  sub Alias_Type_Pls_Integer { return 'Id_254'; }
  sub Alias_Gets { return 'Id_595'; }
  sub Alias_MultipleDeclarationsInSameStatement { return 'Id_258'; }
  sub Alias_RuleOf3_WithCopyAssignator { return 'Id_596'; }
  sub Alias_ImplicitInParameters { return 'Id_372'; }
  sub Alias_ShortAttributeNamesHT { return 'Id_262'; }
  sub Alias_ExceptionVariables { return 'Id_375'; }
  sub Alias_UncommentedProperty { return 'Id_701'; }
  sub Alias_WithoutAutoAssignmentTestAssignmentOperators { return 'Id_263'; }
  sub Alias_UnnecessaryBlockParameter { return 'Id_607'; }
  sub Alias_find_first_of { return 'Id_597'; }
  sub Alias_ShortObjcAttributName { return 'Id_632'; }
  sub Alias_Sql_Update { return 'Id_266'; }
  sub Alias_NativeSQL { return 'Id_524'; }
  sub Alias_HardCodedPaths { return 'Id_270'; }
  sub Alias_CommentLines { return 'Id_271'; }
  sub Alias_BadFileNames { return 'Id_564'; }
  sub Alias_MissingBraces { return 'Id_275'; }
  sub Alias_WithoutPrecision_Varchar2Variable { return 'Id_277'; }
  sub Alias_FileGlobalVariables { return 'Id_281'; }
  sub Alias_OnToManyTablesQueries { return 'Id_503'; }
  sub Alias_Fc_CptCopy { return 'Id_440'; }
  sub Alias_WellNamedLocalVariables { return 'Id_289'; }
  sub Alias_JavaBean { return 'Id_673'; }
  sub Alias_ForinLoop { return 'Id_652'; }
  sub Alias_BugPatterns { return 'Id_291'; }
  sub Alias_BadPtrAccess { return 'Id_292'; }
  sub Alias_FunctionDeclarations_old { return 'Id_356'; }
  sub Alias_Snprintf { return 'Id_598'; }
  sub Alias_UselessTaglib { return 'Id_679'; }
  sub Alias_SimpleCompute { return 'Id_442'; }
  sub Alias_LongArtifact { return 'Id_506'; }
  sub Alias_Base_Loop { return 'Id_297'; }
  sub Alias_AssignmentsInConditionalExpr { return 'Id_299'; }
  sub Alias_ReinterpretCasts { return 'Id_298'; }
  sub Alias_BackPerform { return 'Id_443'; }
  sub Alias_SelectBypassingBuffer { return 'Id_525'; }
  sub Alias_TotalLogicIndents { return 'Id_308'; }
  sub Alias_StdioFunctionCalls { return 'Id_307'; }
  sub Alias_BadLogicIndents { return 'Id_310'; }
  sub Alias_Basex_Or { return 'Id_311'; }
  sub Alias_BadEffectiveParameter { return 'Id_362'; }
  sub Alias_CComments { return 'Id_313'; }
  sub Alias_MultipleComments { return 'Id_692'; }
  sub Alias_Pd_NB_LigneSQL { return 'Id_446'; }
  sub Alias_Halt { return 'Id_315'; }
  sub Alias_StarImport { return 'Id_321'; }
  sub Alias_Fetch { return 'Id_474'; }
  sub Alias_Sql_Commit { return 'Id_323'; }
  sub Alias_MaxChainedPipes { return 'Id_322'; }
  sub Alias_BadFunctionNames { return 'Id_526'; }
  sub Alias_ComplexMethodsHT { return 'Id_326'; }
  sub Alias_TabIndentation { return 'Id_686'; }
  sub Alias_RecSize { return 'Id_476'; }
  sub Alias_Select { return 'Id_328'; }
  sub Alias_ComplexWhen { return 'Id_477'; }
  sub Alias_UnsecureSQLRoutine { return 'Id_507'; }
  sub Alias_ProcedureDeclarations { return 'Id_331'; }
  sub Alias_Goto { return 'Id_333'; }
  sub Alias_LinesOfCode { return 'Id_335'; }
  sub Alias_BadSequenceOrder { return 'Id_684'; }
  sub Alias_StdSQLuse { return 'Id_683'; }
  sub Alias_Provide { return 'Id_527'; }
  sub Alias_LoadDLL { return 'Id_341'; }
  sub Alias_ToManyNestedLoop { return 'Id_479'; }
  sub Alias_FunctionImplementations_old { return 'Id_367'; }
  sub Alias_Base_Forall { return 'Id_343'; }
  sub Alias_Basex_Public { return 'Id_342'; }
  sub Alias_Sql_Rollback { return 'Id_344'; }
  sub Alias_Read { return 'Id_528'; }
  sub Alias_ProcedureImplementations_old { return 'Id_365'; }
  sub Alias_Break { return 'Id_350'; }
  sub Alias_Sql_Drop { return 'Id_351'; }
  sub Alias_ConstantMacroDefinitions { return 'Id_001'; }
  sub Alias_Ls_NbLink01 { return 'Id_376'; }
  sub Alias_WithoutPrecision_NcharVariable { return 'Id_003'; }
  sub Alias_Return { return 'Id_004'; }
  sub Alias_BadZoneInst { return 'Id_377'; }
  sub Alias_Ws_CptCopy { return 'Id_378'; }
  sub Alias_ObjectParameters { return 'Id_009'; }
  sub Alias_Catch { return 'Id_011'; }
  sub Alias_Import { return 'Id_010'; }
  sub Alias_UntaggedParameters { return 'Id_612'; }
  sub Alias_MissingBoxedOrLiteral { return 'Id_636'; }
  sub Alias_SubQueries { return 'Id_481'; }
  sub Alias_BadQualifiedDatabaseObject { return 'Id_482'; }
  sub Alias_DefinitionsInH { return 'Id_015'; }
  sub Alias_AtInLoopAtWhere { return 'Id_529'; }
  sub Alias_MissingInvalidKey { return 'Id_379'; }
  sub Alias_HardCodedValues { return 'Id_530'; }
  sub Alias_WithoutBinarySearch_ReadTable { return 'Id_531'; }
  sub Alias_HtmlComment { return 'Id_693'; }
  sub Alias_BooleanPitfall { return 'Id_611'; }
  sub Alias_NotANSI_Joins { return 'Id_483'; }
  sub Alias_UncommentedEmptyStmts { return 'Id_361'; }
  sub Alias_PrivateAttributes { return 'Id_625'; }
  sub Alias_BadVariableDefinitionCheck { return 'Id_565'; }
  sub Alias_Para { return 'Id_380'; }
  sub Alias_PicTooLong { return 'Id_381'; }
  sub Alias_GlobalVariables { return 'Id_020'; }
  sub Alias_Bad_DDL_DML_Interleaving { return 'Id_485'; }
  sub Alias_Properties { return 'Id_024'; }
  sub Alias_BadVariableNames { return 'Id_654'; }
  sub Alias_Fs_NbFile { return 'Id_383'; }
  sub Alias_WellNamedExportedVariables { return 'Id_027'; }
  sub Alias_LinesNsdk { return 'Id_026'; }
  sub Alias_InstanceOf { return 'Id_025'; }
  sub Alias_ComplexCond { return 'Id_384'; }
  sub Alias_Mov { return 'Id_028'; }
  sub Alias_UnCommentedRoutines { return 'Id_486'; }
  sub Alias_StdDirective { return 'Id_698'; }
  sub Alias_Words { return 'Id_029'; }
  sub Alias_UnloadDLL { return 'Id_030'; }
  sub Alias_VG { return 'Id_386'; }
  sub Alias_ImportAlias { return 'Id_032'; }
  sub Alias_Basex_Private { return 'Id_031'; }
  sub Alias_CommentedVarFunc { return 'Id_522'; }
  sub Alias_EmptyCatches { return 'Id_033'; }
  sub Alias_Sql_Alter { return 'Id_035'; }
  sub Alias_Base_Else { return 'Id_034'; }
  sub Alias_ObjCMethodsImplementation { return 'Id_619'; }
  sub Alias_Base_Exception_Init { return 'Id_036'; }
  sub Alias_CommentBlocs { return 'Id_037'; }
  sub Alias_ShortParameterNamesLT { return 'Id_653'; }
  sub Alias_SelectDistinct { return 'Id_532'; }
  sub Alias_BadMacroNames { return 'Id_040'; }
  sub Alias_FriendMethods { return 'Id_042'; }
  sub Alias_SystemCall { return 'Id_533'; }
  sub Alias_WhenOthers { return 'Id_044'; }
  sub Alias_ProcedureDeclarations_old { return 'Id_353'; }
  sub Alias_CommentLine { return 'Id_388'; }
  sub Alias_Malloc { return 'Id_047'; }
  sub Alias_LinesOfCodeInSpec { return 'Id_357'; }
  sub Alias_FunctionExpressions { return 'Id_667'; }
  sub Alias_Instanceof { return 'Id_049'; }
  sub Alias_BadTmpName { return 'Id_048'; }
  sub Alias_WithMissingParameterNameBlock { return 'Id_609'; }
  sub Alias_WithoutPrecision_Nvarchar2Variable { return 'Id_050'; }
  sub Alias_Implementation { return 'Id_616'; }
  sub Alias_WithoutReturningStarThisAssignmentOperators { return 'Id_051'; }
  sub Alias_WithoutSizeCins { return 'Id_052'; }
  sub Alias_Pd_NbGOTO { return 'Id_390'; }
  sub Alias_WithoutInterfaceImplementation { return 'Id_599'; }
  sub Alias_ShortVarName { return 'Id_054'; }
  sub Alias_LinesOfCodeInBody { return 'Id_366'; }
  sub Alias_ComplexQueries { return 'Id_489'; }
  sub Alias_Eval { return 'Id_670'; }
  sub Alias_StdExpression { return 'Id_696'; }
  sub Alias_CaseLike_Else { return 'Id_060'; }
  sub Alias_Strtrns { return 'Id_600'; }
  sub Alias_BodyExceptionVariables { return 'Id_063'; }
  sub Alias_UnmanagedSQLRoutine { return 'Id_490'; }
  sub Alias_UnCommentedColumns { return 'Id_491'; }
  sub Alias_NewMethodDeclaration { return 'Id_629'; }
  sub Alias_PrivateInheritances { return 'Id_066'; }
  sub Alias_SQLWhere { return 'Id_492'; }
  sub Alias_Type_Positive { return 'Id_068'; }
  sub Alias_OddSetptr { return 'Id_070'; }
  sub Alias_MissingCatch { return 'Id_708'; }
  sub Alias_WithThrowDestructors { return 'Id_071'; }
  sub Alias_FunctionMethodDeclarations { return 'Id_072'; }
  sub Alias_Type_Row { return 'Id_073'; }
  sub Alias_ComplexArtifact { return 'Id_493'; }
  sub Alias_ObjectDeclaration { return 'Id_668'; }
  sub Alias_MissingImmediateFuncCallWrapping { return 'Id_647'; }
  sub Alias_XmlScriptlet { return 'Id_680'; }
  sub Alias_ReturnTags { return 'Id_078'; }
  sub Alias_StdDeclaration { return 'Id_694'; }
  sub Alias_MissingFileClose { return 'Id_458'; }
  sub Alias_Base_End { return 'Id_080'; }
  sub Alias_Basex_Then { return 'Id_081'; }
  sub Alias_BadEffectiveSecondParameter { return 'Id_355'; }
  sub Alias_BodyPackage { return 'Id_085'; }
  sub Alias_AssignmentsInFunctionCall { return 'Id_086'; }
  sub Alias_MissingErrorPage { return 'Id_671'; }
  sub Alias_UncheckedReturn { return 'Id_534'; }
  sub Alias_UnexpectedSimpleQuoteStr { return 'Id_689'; }
  sub Alias_Constructors { return 'Id_092'; }
  sub Alias_Base_If { return 'Id_091'; }
  sub Alias_MissingBreakInSwitch { return 'Id_095'; }
  sub Alias_SpecPackage { return 'Id_093'; }
  sub Alias_Type_Char_Base { return 'Id_096'; }
  sub Alias_ForbiddenOverloadedOperators { return 'Id_098'; }
  sub Alias_SpecExceptionVariables { return 'Id_101'; }
  sub Alias_BadTldContent { return 'Id_678'; }
  sub Alias_WithMultiExprPerLine_Where { return 'Id_496'; }
  sub Alias_BadJavaScriptInclude { return 'Id_702'; }
  sub Alias_IllegalThrows { return 'Id_104'; }
  sub Alias_StructuredTypedefs { return 'Id_107'; }
  sub Alias_OnError { return 'Id_106'; }
  sub Alias_FetchNextCursor { return 'Id_551'; }
  sub Alias_ConstantDefinitions { return 'Id_111'; }
  sub Alias_Basex_And { return 'Id_110'; }
  sub Alias_Base_For { return 'Id_109'; }
  sub Alias_ToManyNestedIf { return 'Id_459'; }
  sub Alias_AnonymousBlocs { return 'Id_374'; }
  sub Alias_MissingOnError { return 'Id_460'; }
  sub Alias_EmptyProgram { return 'Id_535'; }
  sub Alias_Pd_CptCopy { return 'Id_399'; }
  sub Alias_UselessForLoop { return 'Id_566'; }
  sub Alias_LowCommentedRoutines { return 'Id_550'; }
  sub Alias_PackageBodyVariables { return 'Id_118'; }
  sub Alias_MissingShortTag { return 'Id_690'; }
  sub Alias_Base_Return { return 'Id_119'; }
  sub Alias_Fs_CptCopy { return 'Id_401'; }
  sub Alias_BadSpacing { return 'Id_120'; }
  sub Alias_Fclose { return 'Id_122'; }
  sub Alias_Type_Real { return 'Id_125'; }
  sub Alias_New { return 'Id_127'; }
  sub Alias_WithoutSemiColumn_End { return 'Id_126'; }
  sub Alias_NumericalOrderBy { return 'Id_498'; }
  sub Alias_NonObjectType { return 'Id_128'; }
  sub Alias_UnnecessaryFinalModifier { return 'Id_567'; }
  sub Alias_InsertWithoutColumnsList { return 'Id_499'; }
  sub Alias_BugPatternsTrace { return 'Id_131'; }
  sub Alias_Dbms_Sql_Open { return 'Id_132'; }
  sub Alias_Realpath { return 'Id_601'; }
  sub Alias_SpecObjectType { return 'Id_133'; }
  sub Alias_NestedSelect { return 'Id_536'; }
  sub Alias_EmptyArtifact { return 'Id_537'; }
  sub Alias_BodyType { return 'Id_136'; }
  sub Alias_WithoutPrecision_VarcharVariable { return 'Id_138'; }
  sub Alias_Finalize { return 'Id_139'; }
  sub Alias_ContigusLevel { return 'Id_404'; }
  sub Alias_Basex_Subtype { return 'Id_141'; }
  sub Alias_UnexpectedDoubleQuoteStr { return 'Id_640'; }
  sub Alias_MethodImplementations { return 'Id_538'; }
  sub Alias_InstanciationWithNew { return 'Id_622'; }
  sub Alias_ImpreciseNumericDeclaration { return 'Id_462'; }
  sub Alias_ProcessStatement { return 'Id_463'; }
  sub Alias_SuspiciousComments { return 'Id_144'; }
  sub Alias_Type_Long { return 'Id_146'; }
  sub Alias_RiskyCatches { return 'Id_147'; }
  sub Alias_Realloc { return 'Id_148'; }
  sub Alias_ShortClassNamesHT { return 'Id_150'; }
  sub Alias_WithoutTitleFetch { return 'Id_464'; }
  sub Alias_UpTo1Row { return 'Id_539'; }
  sub Alias_BreakPoint { return 'Id_540'; }
  sub Alias_Streadd { return 'Id_602'; }
  sub Alias_Default { return 'Id_155'; }
  sub Alias_MissingHashcode { return 'Id_156'; }
  sub Alias_BadInit { return 'Id_408'; }
  sub Alias_ImplicitClosing { return 'Id_706'; }
  sub Alias_Close { return 'Id_160'; }
  sub Alias_BadObjCAttributeNames { return 'Id_630'; }
  sub Alias_ParaVide { return 'Id_409'; }
  sub Alias_IncrementerJumblingInLoop { return 'Id_568'; }
  sub Alias_NotOpInWhereClause { return 'Id_541'; }
  sub Alias_MultipleStatementsOnSameLine { return 'Id_161'; }
  sub Alias_OverloadEquals { return 'Id_163'; }
  sub Alias_WhithoutPrivateDefaultConstructorUtilityClass { return 'Id_604'; }
  sub Alias_BadConstructorNames { return 'Id_569'; }
  sub Alias_Compute { return 'Id_411'; }
  sub Alias_Pd_NBOPdiff { return 'Id_412'; }
  sub Alias_LonelyVariableInString { return 'Id_570'; }
  sub Alias_CommentedOutCode { return 'Id_168'; }
  sub Alias_SQLDistinctOrder { return 'Id_413'; }
  sub Alias_Pd_NbLgBl { return 'Id_414'; }
  sub Alias_TestUnameAgainstSpecificValue { return 'Id_542'; }
  sub Alias_BadSetTimeout { return 'Id_665'; }
  sub Alias_LinesInBody { return 'Id_370'; }
  sub Alias_ObjCUninitializedLocalVariables { return 'Id_627'; }
  sub Alias_CallToBlockingFunction { return 'Id_605'; }
  sub Alias_IllegalException { return 'Id_174'; }
  sub Alias_Pd_BoucleFor { return 'Id_416'; }
  sub Alias_ClassNameIsNotFileName { return 'Id_571'; }
  sub Alias_BadObjCClassNames { return 'Id_634'; }
  sub Alias_DynamicQueries { return 'Id_543'; }
  sub Alias_MissingSpaceInTag { return 'Id_687'; }
  sub Alias_UnnecessaryBlockreturnType { return 'Id_608'; }
  sub Alias_LongLines120 { return 'Id_572'; }
  sub Alias_Exit { return 'Id_179'; }
  sub Alias_SQLOrderBy { return 'Id_418'; }
  sub Alias_ObsoleteKeywordPD { return 'Id_419'; }
  sub Alias_MissingWhenOthers { return 'Id_180'; }
  sub Alias_ForbiddenReferenceReturningOperators { return 'Id_182'; }
  sub Alias_SQLComplexWhereClause { return 'Id_420'; }
  sub Alias_ObsoleteKeywordID { return 'Id_421'; }
  sub Alias_NBOPTot { return 'Id_422'; }
  sub Alias_MultilineString { return 'Id_641'; }
  sub Alias_Tab { return 'Id_423'; }
  sub Alias_TotalObjCParameters { return 'Id_615'; }
  sub Alias_WithSeveralExit_Loop { return 'Id_190'; }
  sub Alias_TotalParameters { return 'Id_359'; }
  sub Alias_DynamicCall { return 'Id_424'; }
  sub Alias_WithTooManyColumnsTables { return 'Id_502'; }
  sub Alias_FriendClasses { return 'Id_195'; }
  sub Alias_MissingIncludeProtections { return 'Id_196'; }
  sub Alias_String { return 'Id_466'; }
  sub Alias_WithExitFunctions { return 'Id_198'; }
  sub Alias_Lines { return 'Id_425'; }
  sub Alias_MissingEndEVA { return 'Id_426'; }
  sub Alias_WithParametersModeOut_Functions { return 'Id_203'; }
  sub Alias_NotTestedSQLCODE { return 'Id_467'; }
  sub Alias_CompareToEmptyString { return 'Id_206'; }
  sub Alias_Statements { return 'Id_208'; }
  sub Alias_EmptyInclude { return 'Id_544'; }
  sub Alias_WithTooMuchParametersMethods { return 'Id_211'; }
  sub Alias_UnsecuredWebsite { return 'Id_703'; }
  sub Alias_BadObjectDeclaration { return 'Id_649'; }
  sub Alias_WithSqlCode_WhenOthers { return 'Id_218'; }
  sub Alias_SuspiciousLastCase { return 'Id_221'; }
  sub Alias_StructDefinitions { return 'Id_223'; }
  sub Alias_Base_Begin { return 'Id_222'; }
  sub Alias_ShortSegmentNamesLT { return 'Id_225'; }
  sub Alias_CCastUses { return 'Id_227'; }
  sub Alias_MisplacedInnerFuncDecl { return 'Id_645'; }
  sub Alias_NullStatement { return 'Id_468'; }
  sub Alias_FunctionCallInLoopTest { return 'Id_651'; }
  sub Alias_Interface { return 'Id_631'; }
  sub Alias_PublicFonctionsProcedures { return 'Id_373'; }
  sub Alias_phpinfo { return 'Id_573'; }
  sub Alias_MultAffect { return 'Id_431'; }
  sub Alias_NonPrivateDataMember { return 'Id_606'; }
  sub Alias_UnconditionalCondition { return 'Id_574'; }
  sub Alias_NBOPdiff { return 'Id_432'; }
  sub Alias_ConstLit { return 'Id_433'; }
  sub Alias_DistinctWords { return 'Id_240'; }
  sub Alias_End { return 'Id_470'; }
  sub Alias_Scanf { return 'Id_603'; }
  sub Alias_Base_While { return 'Id_241'; }
  sub Alias_XmlDirective { return 'Id_699'; }
  sub Alias_NotPureKsh { return 'Id_242'; }
  sub Alias_ParentInterfaces { return 'Id_243'; }
  sub Alias_WithoutLabel_End { return 'Id_246'; }
  sub Alias_BadLayout { return 'Id_628'; }
  sub Alias_RequiredParamsBeforeOptional { return 'Id_575'; }
  sub Alias_AlphaNumCommentLines { return 'Id_251'; }
  sub Alias_BadAttributeNames { return 'Id_250'; }
  sub Alias_FunctionImplementations { return 'Id_249'; }
  sub Alias_InterfaceDefinitions { return 'Id_255'; }
  sub Alias_CuriousFilePb { return 'Id_435'; }
  sub Alias_Pragmas { return 'Id_256'; }
  sub Alias_If { return 'Id_260'; }
  sub Alias_BadDeclarationOrder { return 'Id_259'; }
  sub Alias_Type_Rowid { return 'Id_261'; }
  sub Alias_LowCommentedRootCode { return 'Id_576'; }
  sub Alias_MissingThrowsTags { return 'Id_577'; }
  sub Alias_Pd_NBOPTot { return 'Id_436'; }
  sub Alias_ModuleImplementations { return 'Id_545'; }
  sub Alias_LogicalLinesOfCode { return 'Id_265'; }
  sub Alias_AndOr { return 'Id_264'; }
  sub Alias_CodeCommentLine { return 'Id_437'; }
  sub Alias_ReadTable { return 'Id_546'; }
  sub Alias_Type_Binary_Integer { return 'Id_267'; }
  sub Alias_DuplicatedParaName { return 'Id_438'; }
  sub Alias_Type_Smallint { return 'Id_268'; }
  sub Alias_BackGoto { return 'Id_439'; }
  sub Alias_Type_Clob { return 'Id_269'; }
  sub Alias_Sql_Connect { return 'Id_273'; }
  sub Alias_WithReturnOutsideExceptionHandler_Procedure { return 'Id_272'; }
  sub Alias_UpperCaseKeywords { return 'Id_578'; }
  sub Alias_Sql_Delete { return 'Id_274'; }
  sub Alias_ShortClassNamesLT { return 'Id_276'; }
  sub Alias_ObjCMethodsDeclaration { return 'Id_620'; }
  sub Alias_InlineMethods { return 'Id_278'; }
  sub Alias_BadParameterNames { return 'Id_614'; }
  sub Alias_UnCommentedClasses { return 'Id_580'; }
  sub Alias_Queries { return 'Id_579'; }
  sub Alias_IncrDecrOperatorComplexUses { return 'Id_279'; }
  sub Alias_MultipleReturnFunctionsMethods { return 'Id_280'; }
  sub Alias_Declare { return 'Id_473'; }
  sub Alias_TruncateTable { return 'Id_504'; }
  sub Alias_LoopInto { return 'Id_547'; }
  sub Alias_LinesOfPrepro { return 'Id_626'; }
  sub Alias_WithoutKshFirstLine { return 'Id_283'; }
  sub Alias_UnauthorizedPrototypeModification { return 'Id_660'; }
  sub Alias_WithoutFinalReturn_Functions { return 'Id_284'; }
  sub Alias_ShortMethodNamesHT { return 'Id_285'; }
  sub Alias_Dynamic { return 'Id_286'; }
  sub Alias_Using { return 'Id_287'; }
  sub Alias_WithoutFormatSizeScanfs { return 'Id_288'; }
  sub Alias_MissingWhereClause { return 'Id_548'; }
  sub Alias_Delete { return 'Id_290'; }
  sub Alias_BadObjCMethodNames { return 'Id_633'; }
  sub Alias_WithoutParameter_Procedures { return 'Id_293'; }
  sub Alias_MissingClassConstructor { return 'Id_295'; }
  sub Alias_CompareToNull { return 'Id_296'; }
  sub Alias_Pd_CptInst { return 'Id_441'; }
  sub Alias_FetchInLoop { return 'Id_505'; }
  sub Alias_BadDynamicClassDefinitions { return 'Id_300'; }
  sub Alias_Max_ComplexMethodsVg { return 'Id_301'; }
  sub Alias_NullStringComparisons { return 'Id_302'; }
  sub Alias_Type_Number { return 'Id_303'; }
  sub Alias_Switch { return 'Id_304'; }
  sub Alias_Type_Char { return 'Id_305'; }
  sub Alias_Strdup { return 'Id_306'; }
  sub Alias_BasicTypeUses { return 'Id_309'; }
  sub Alias_WithoutPrecision_CharVariable { return 'Id_312'; }
  sub Alias_VGmoyen { return 'Id_444'; }
  sub Alias_NegativeComparison { return 'Id_610'; }
  sub Alias_BadEffectiveThirdParameter { return 'Id_368'; }
  sub Alias_Pd_CptNivMax { return 'Id_445'; }
  sub Alias_Base_Decode { return 'Id_314'; }
  sub Alias_FixedSizeArrays { return 'Id_316'; }
  sub Alias_MisplacedVarStatement { return 'Id_659'; }
  sub Alias_BadToAlign { return 'Id_447'; }
  sub Alias_LocalVariables { return 'Id_317'; }
  sub Alias_BadDeclareUse { return 'Id_318'; }
  sub Alias_TernaryOperators { return 'Id_320'; }
  sub Alias_Ws_NbData77 { return 'Id_448'; }
  sub Alias_UncheckedInit { return 'Id_623'; }
  sub Alias_Getopt { return 'Id_324'; }
  sub Alias_CPPKeywords { return 'Id_325'; }
  sub Alias_Loop { return 'Id_327'; }
  sub Alias_NoExitInParaRefByThru { return 'Id_449'; }
  sub Alias_SelectAll { return 'Id_475'; }
  sub Alias_UnexpectedThis { return 'Id_662'; }
  sub Alias_WithExit_ConditionalLoops { return 'Id_329'; }
  sub Alias_Base_Do { return 'Id_332'; }
  sub Alias_ExitInInclude { return 'Id_552'; }
  sub Alias_From { return 'Id_508'; }
  sub Alias_UnnecessaryConcat { return 'Id_581'; }
  sub Alias_BlankLines { return 'Id_371'; }
  sub Alias_BadEndClauseAlign { return 'Id_450'; }
  sub Alias_LongLines132 { return 'Id_337'; }
  sub Alias_Ws_NbData01 { return 'Id_451'; }
  sub Alias_EndSelect { return 'Id_549'; }
  sub Alias_ComplexOperands { return 'Id_339'; }
  sub Alias_ConstructorWithReturn { return 'Id_583'; }
  sub Alias_ComplexRootCode { return 'Id_582'; }
  sub Alias_MissingVarFree { return 'Id_478'; }
  sub Alias_VarNotUsed { return 'Id_452'; }
  sub Alias_ParentClasses { return 'Id_345'; }
  sub Alias_Sql_Execute { return 'Id_346'; }
  sub Alias_Fopen { return 'Id_347'; }
  sub Alias_FunctionOutParameters { return 'Id_363'; }
  sub Alias_Else { return 'Id_348'; }
  sub Alias_BadMethodNames { return 'Id_349'; }
  sub Alias_InlineComments { return 'Id_709'; }
  sub Alias_GlobalVariableHidding { return 'Id_710'; }
  sub Alias_OverridenBuiltInException { return 'Id_711'; }
  sub Alias_ConflictingImports { return 'Id_712'; }
  sub Alias_MultipleImports { return 'Id_713'; }
  sub Alias_BadAliasAgreement { return 'Id_714'; }
  sub Alias_UnusedImports { return 'Id_715'; }
  sub Alias_BadParentConstructorInvocation { return 'Id_716'; } # FIXME : check if the counter is really used !!!
  sub Alias_FromScratchClasses { return 'Id_717'; }
  sub Alias_MagicMethodsCalls { return 'Id_718'; }
  sub Alias_ExplicitComparisonToSingleton { return 'Id_719'; }
  sub Alias_DeprecatedOperator { return 'Id_720'; }
  sub Alias_BadIdenticalOperatorUse { return 'Id_721'; }
  sub Alias_InvertedLogic { return 'Id_722'; }
  sub Alias_RepetitionInComparison { return 'Id_723'; }
  sub Alias_TrySizeAverage { return 'Id_724'; }
  sub Alias_EmptyReturn { return 'Id_725'; }
  sub Alias_BadGetterSetter { return 'Id_726'; }
  sub Alias_MissingParentConstructor { return 'Id_727'; }
  sub Alias_BadStaticOrClassMethods { return 'Id_728'; }
  sub Alias_ExtraneousSpaces { return 'Id_729'; }
  sub Alias_MissingSpaces { return 'Id_730'; }
  sub Alias_MissingBlankLines { return 'Id_731'; }
  sub Alias_TrailingSpaces { return 'Id_732'; }
  sub Alias_ContinuationLines { return 'Id_733'; }
  sub Alias_PercentStringFormat { return 'Id_734'; }
  sub Alias_AutomaticNumberingInStringsFields { return 'Id_735'; }
  sub Alias_MixedStringsStyle { return 'Id_736'; }
  sub Alias_SpacesInStringReplacementFields { return 'Id_737'; }
  sub Alias_LocalVarAverage { return 'Id_738'; }
  sub Alias_MethodsAverage { return 'Id_739'; }
  sub Alias_MultilineConditions { return 'Id_740'; }
  sub Alias_BadBoundary { return 'Id_741'; }
  sub Alias_LoopWithElseWithoutBreak { return 'Id_742'; }
  sub Alias_FunctionNameLengthAverage { return 'Id_743'; }
  sub Alias_MethodNameLengthAverage { return 'Id_744'; }
  sub Alias_ConcatInLoop { return 'Id_745'; }
  sub Alias_UnexpectedSemicolon { return 'Id_746'; }
  sub Alias_DateUtilsTruncate { return 'Id_747'; }
  sub Alias_RunFinalizersOnExit { return 'Id_748'; }
  sub Alias_NestedTryCatches { return 'Id_749'; }
  sub Alias_EqualsNotTestingParameter { return 'Id_750'; }
  sub Alias_OnlyRethrowingCatches { return 'Id_751'; }
  sub Alias_EmptyMethods  { return 'Id_752'; }
  sub Alias_CaseLengthAverage { return 'Id_753'; }
  sub Alias_SmallSwitchCase { return 'Id_754'; }
  sub Alias_UnconditionalJump { return 'Id_755'; }
  sub Alias_EqualityInLoopCondition { return 'Id_756'; }
  sub Alias_FunctionsUsingEllipsis { return 'Id_757'; }
  sub Alias_LoopCounterModification  { return 'Id_758'; }
  sub Alias_TotalAttributes  { return 'Id_759'; }
  sub Alias_PrimitiveTypeWrapperInstanciation  { return 'Id_760'; }
  sub Alias_EmptyClasses  { return 'Id_761'; }
  sub Alias_UnexpectedAbstractClass  { return 'Id_762'; }
  sub Alias_ProtectedMemberInFinalClass  { return 'Id_763'; }
  sub Alias_PublicConstructorInUtilityClass { return 'Id_764'; }
  sub Alias_OctalLiteralValues  { return 'Id_765'; }
  sub Alias_LCLiteralSuffixes  { return 'Id_766'; }
  sub Alias_SuspiciousCommentSyntax { return 'Id_768'; }
  sub Alias_BadLiteralConstant { return 'Id_769'; }
  sub Alias_MissingTabSize { return 'Id_770'; }
  sub Alias_WithoutCaseSwitch { return 'Id_771'; }
  sub Alias_OverFlowingLoopCounter { return 'Id_772'; }
  sub Alias_NonTerminalCatchAll { return 'Id_774'; }
  sub Alias_MisplacedInclude { return 'Id_775'; }
  sub Alias_MisplacedDefine { return 'Id_776'; }
  sub Alias_Undef { return 'Id_777'; }
  sub Alias_ImplementationDefinedLibraryUse { return 'Id_778'; }
  sub Alias_SwitchNested { return 'Id_319'; }
  sub Alias_VariableShadow { return 'Id_330'; }
  sub Alias_SwitchDefaultMisplaced { return 'Id_041'; }
  sub Alias_ErrorWithoutThrow { return 'Id_002'; }
  sub Alias_BadCaseLogical { return 'Id_018'; }
  sub Alias_BadInterfaceConstructor { return 'Id_056'; }
  sub Alias_MultilineBreak { return 'Id_059'; }
  sub Alias_ParameterShadow { return 'Id_065'; }
  sub Alias_BadReturnStatement { return 'Id_099'; }
  sub Alias_Var { return 'Id_153'; }
  sub Alias_OptionalProperty { return 'Id_187'; }
  sub Alias_Throw { return 'Id_191'; }
  sub Alias_ParametersAverage { return 'Id_779'; }
  sub Alias_Let { return 'Id_201'; }
  sub Alias_Const { return 'Id_204'; }
  sub Alias_DangerousTry { return 'Id_038'; }
  sub Alias_DuplicatedString { return 'Id_143'; }
  sub Alias_UnexpectedCast { return 'Id_209'; }
  sub Alias_UnexpectedBreakStatement { return 'Id_216'; }
  sub Alias_NestedTernary { return 'Id_229'; }
  sub Alias_BadEnumNames { return 'Id_238'; }
  sub Alias_BadProtocolNames { return 'Id_257'; }
  sub Alias_BadConstantNames { return 'Id_282'; }
  sub Alias_FieldNameIsClassName { return 'Id_294'; }
  sub Alias_ImplicitReturn { return 'Id_334'; }
  sub Alias_NestedClosure { return 'Id_336'; }
  sub Alias_ToManyNestedControlFlow { return 'Id_338'; }
  sub Alias_DeadCode { return 'Id_780'; }
  sub Alias_MisplacedParam { return 'Id_340'; }
  sub Alias_HardCodedUrl { return 'Id_781'; }
  sub Alias_SwitchLengthAverage { return 'Id_782'; }
  sub Alias_RoutineNameLengthAverage { return 'Id_783'; }
  sub Alias_AttributeNameLengthAverage { return 'Id_784'; }
  sub Alias_ParameterNameLengthAverage { return 'Id_785'; }
  sub Alias_ClassNameLengthAverage { return 'Id_786'; }
  sub Alias_UnusedPrivateMethods { return 'Id_787'; }
  sub Alias_UnusedLocalVariables { return 'Id_788'; }
  sub Alias_WithUnexpectedBodyFunctions { return 'Id_789'; }
  sub Alias_CollapsibleIf { return 'Id_790'; }
  sub Alias_ConditionComplexityAverage { return 'Id_791'; }
  sub Alias_RoutinesLengthIndicator { return 'Id_792'; }
  sub Alias_CaseLengthIndicator { return 'Id_793'; }
  sub Alias_LabeledReturnsInLambda { return 'Id_794'; }
  sub Alias_LabeledReturnEndingLambda { return 'Id_795'; }
  sub Alias_MissingExpressionForm { return 'Id_796'; }
  sub Alias_BadNullableCheck { return 'Id_797'; }
  sub Alias_LongElsif { return 'Id_798'; }
  sub Alias_UselessTypeSpecification { return 'Id_799'; }
  sub Alias_VgAverage { return 'Id_800'; }
  sub Alias_GenericCatches { return 'Id_801'; }
  sub Alias_SuspiciousOperator { return 'Id_812'; }
  sub Alias_DuplicatedCondition { return 'Id_813'; }
  sub Alias_BadValuesOperator { return 'Id_814'; }
  sub Alias_SelfAssigned { return 'Id_815'; }
  sub Alias_OverDepthAverage { return 'Id_809'; }
  sub Alias_MissingShortVariableDeclaration { return 'Id_816'; }
  sub Alias_UnnamedData { return 'Id_817'; }
  sub Alias_UnusedNamedReceiver { return 'Id_818'; }
  sub Alias_AbstractClassWithPublicConstructor { return 'Id_767'; }
  sub Alias_PublicFinalizeMethod { return 'Id_773'; }
  sub Alias_NestedForLoop { return 'Id_802'; }
  sub Alias_DynamicType { return 'Id_803'; }
  sub Alias_ClosureAsLastMethodParameter { return 'Id_804'; }
  sub Alias_SuspiciousDestructuringAssignment { return 'Id_805'; }
  sub Alias_CouldBeElvis { return 'Id_806'; }
  sub Alias_ParameterUpdate { return 'Id_807'; }
  sub Alias_AssignmentToStaticFieldFromInstanceMethod { return 'Id_808'; }
  sub Alias_MissingEquals { return 'Id_810'; }
  sub Alias_LongCase { return 'Id_811'; }
  sub Alias_VariableNameLengthAverage { return 'Id_819'; }
  sub Alias_LargeSwitches { return 'Id_820'; }
  sub Alias_TabInsideIndentation { return 'Id_821'; }
  sub Alias_FormBodyIndentation { return 'Id_822'; }
  sub Alias_GlobalDefInsideFunctions { return 'Id_823'; }
  sub Alias_BadVariableUpdate { return 'Id_824'; }
  sub Alias_BadArityIndentation { return 'Id_825'; }
  sub Alias_BadMultiArityOrder { return 'Id_826'; } 
  sub Alias_BadStringAsHaskKey{ return "Id_827"; }
  sub Alias_BadSwitchForm { return "Id_828"; }
  sub Alias_IfShouldBeWhen{ return "Id_829"; }
  sub Alias_LongFunctionLiteral{ return "Id_830"; }
  sub Alias_MissingSpaceAfterCommentDelimiter{ return "Id_831"; }
  sub Alias_OperatorCouldBeFunction{ return "Id_832"; }
  sub Alias_ParameterIndentation{ return "Id_833"; }
  sub Alias_ParenthesesSpacing{ return "Id_834"; }
  sub Alias_TrailingParentheses{ return "Id_835"; }
  sub Alias_UnexpectedConditionalLet{ return "Id_836"; }
  sub Alias_UselessFullSyntaxMetadata{ return "Id_837"; }
  sub Alias_BodyBeginOnSameLineThanParams{ return "Id_838"; }
  sub Alias_BadTypeNames{ return "Id_839"; }
  sub Alias_BadConversionFunctionNames{ return "Id_840"; }
  sub Alias_BadDynamicVarNames{ return "Id_841"; }
  sub Alias_DeprecatedReferenceInNamespace{ return "Id_842"; }
  sub Alias_MissingIdiomaticAliases{ return "Id_843"; }
  sub Alias_MethodsLengthAverage{ return "Id_844"; }
  sub Alias_ArtifactDepthAverage{ return "Id_845"; }
  sub Alias_TopLevelClasses{ return "Id_846"; }
  sub Alias_BreakCase{ return "Id_847"; }
  sub Alias_ThrowInFinally{ return "Id_848"; }
  sub Alias_ThrowInDestructor{ return "Id_849"; }
  sub Alias_LostInitialization{ return "Id_850"; }
  sub Alias_UnusedAttributes{ return "Id_851"; }
  sub Alias_FieldShadow{ return "Id_852"; }
  
1;

